#!/usr/bin/env bash

cd $OPENSHIFT_REPO_DIR
php composer.phar update
php app/console doctrine:schema:update --env=prod --force
php app/console cache:clear --env=prod

chmod -R 0777 $OPENSHIFT_REPO_DIR/app/cache
chmod -R 0777 $OPENSHIFT_REPO_DIR/app/logs

