wbs_fussball_api_alle_ligen:
    path:     /liga/{format}
    defaults: { _controller: WBSFussballApiBundle:Liga:all }

wbs_fussball_api_liga:
    path:     /liga/{format}/{id}
    defaults: { _controller: WBSFussballApiBundle:Liga:show }

wbs_fussball_api_liga_eintragen:
    path:    /eintragen/liga/
    defaults: { _controller: WBSFussballApiBundle:Liga:create }
    methods: [POST]

wbs_fussball_api_alle_saisons:
    path:     /saison/{format}
    defaults: { _controller: WBSFussballApiBundle:LigaSaison:all }

wbs_fussball_api_saison:
    path:     /saison/{format}/{id}
    defaults: { _controller: WBSFussballApiBundle:LigaSaison:show }

wbs_fussball_api_saison_eintragen:
    path:    /eintragen/saison/
    defaults: { _controller: WBSFussballApiBundle:LigaSaison:create }
    methods: [POST]

wbs_fussball_api_alle_vereine:
    path:     /verein/{format}
    defaults: { _controller: WBSFussballApiBundle:Verein:all }
    
wbs_fussball_api_verein:
    path:     /verein/{format}/{id}
    defaults: { _controller: WBSFussballApiBundle:Verein:show }

wbs_fussball_api_verein_eintragen:
    path:     /eintragen/verein/
    defaults: { _controller: WBSFussballApiBundle:Verein:create }

wbs_fussball_api_alle_spieler:
    path:     /spieler/{format}
    defaults: { _controller: WBSFussballApiBundle:Spieler:all }

wbs_fussball_api_spieler:
    path:     /spieler/{format}/{id}
    defaults: { _controller: WBSFussballApiBundle:Spieler:show }

wbs_fussball_api_spieler_eintragen:
    path:     /eintragen/spieler
    defaults: { _controller: WBSFussballApiBundle:Spieler:create }