<?php

namespace WBS\Fussball\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigaRepository extends EntityRepository
{
}
