<?php

namespace WBS\Fussball\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigaSaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigaSaisonRepository extends EntityRepository
{
}
